name: CI for releases

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  quality-gate:
    name: Release quality gate
    uses: ./.github/workflows/install-lint-build.yml

  publish-images:
    name: Publish container images
    needs: [quality-gate]
    permissions:
      actions: write
      contents: read
    uses: ./.github/workflows/build-and-push.yml
    secrets:
      PAT: ${{ secrets.PAT }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
