name: CI for releases

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  install-test-build:
    uses: ./.github/workflows/install-test-build.yml

  full-env-e2e:
    needs: [install-test-build]
    uses: ./.github/workflows/full-env-e2e.yml

  minimal-env-e2e:
    needs: [install-test-build]
    uses: ./.github/workflows/minimal-env-e2e.yml

  build-and-push-docker-image:
    needs: [install-test-build, full-env-e2e, minimal-env-e2e]
    uses: ./.github/workflows/build-and-push.yml
    secrets:
      PAT: ${{ secrets.PAT }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
